#!/usr/bin/env python3

# Vadim Zyamalov <vadim.zyamalov@gmail.com>
# Licensed under the conditions of MIT license

import os
import sys
from xdg.DesktopEntry import DesktopEntry as DE
from subprocess import Popen, PIPE


def split_escape(string, delim=' ', escape='\\'):
    tmp = string.split(delim)
    res = []
    i = 0
    while i < len(tmp):
        if tmp[i].endswith(escape) and (i + 1 < len(tmp)):
            res.append('{} {}'.format(tmp[i], tmp[i+1]))
            i += 1
        else:
            res.append(tmp[i])
        i += 1
    return res


def dirlist():
    res = []
    try:
        res.append(os.environ['XDG_DATA_HOME'])
    except KeyError:
        res.append('{}/.local/share/applications'.format(os.environ['HOME']))
    try:
        res.extend(os.environ['XDG_DATA_DIRS'].split(':'))
    except KeyError:
        res.extend('/usr/local/share/applications:/usr/share/applications'.split(':'))
    return res


def appdict():
    res = {}
    for path in dirlist():
        try:
            files = os.listdir(path)
        except FileNotFoundError:
            continue
        for curfile in files:
            if not curfile.endswith('.desktop'):
                continue
            curdesktop = DE('{}/{}'.format(path, curfile))
            if not curdesktop.getName() in res:
                res[curdesktop.getName()] = {'exec': split_escape(curdesktop.getExec())[0],
                                             'term': curdesktop.getTerminal()}
    return res


def applist(appdict):
    res = []
    for key in appdict.keys():
        res.append(key)
    res.sort()
    return res


def calldmenu(apps):
    dmenu = ['dmenu']
    dmenu.extend(sys.argv[1:])
    appstr = ('\n'.join(apps)).encode('utf8')
    dmenup = Popen(dmenu, stdin=PIPE, stdout=PIPE)
    (res, err) = dmenup.communicate(input=appstr)
    exitcode = dmenup.wait()
    if not exitcode:
        return res.decode('utf8').strip()
    else:
        return ''


if __name__ == '__main__':
    try:
        term = os.environ['TERMINAL']
    except KeyError:
        term = 'xterm'
    apps = appdict()
    res = calldmenu(applist(apps))
    if res:
        if apps[res]['term']:
            Popen([term, '-e', apps[res]['exec']])
        else:
            Popen([apps[res]['exec']])
